{% set version = "0.2.62" %}

package:
  name: tidk
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('tidk', max_pin="x.x") }}

source:
  url: https://github.com/tolkit/telomeric-identifier/archive/v{{ version }}.tar.gz
  sha256: 2419ff00ffa7221a7d7f359d7710642b7e0ad38c7505568cf220d932e48d1bcc

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - rust >=1.52
    - pkg-config  # [osx]

  host:
    - openssl

test:
  commands:
    - tidk --help
    - tidk --version

about:
  home: https://github.com/tolkit/telomeric-identifier
  license: MIT
  license_family: MIT
  summary: |
    Identify and find telomeres, or telomeric repeats in a genome.
